# Generated by Django 5.2 on 2026-08-23 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_item_options_item_is_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.TextField(
                help_text="Имя должнобыть больше, чем из 2х букв",
                validators=[django.core.validators.MinLengthValidator(2)],
                verbose_name="Имя",
            ),
        ),
    ]
