# Generated by Django 5.2 on 2026-08-24 13:55

import catalog.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_item_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.TextField(
                help_text="Имя должнобыть больше, чем из 2х букв",
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    catalog.validators.validators_item,
                ],
                verbose_name="Имя",
            ),
        ),
    ]
