# Generated by Django 5.2 on 2026-08-25 11:13

import catalog.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_item_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.CharField(
                blank=True,
                default="",
                validators=[django.core.validators.MaxLengthValidator(150)],
                verbose_name="Слаг",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Описание должно быть не больше чем 150 букв",
                validators=[
                    django.core.validators.MaxLengthValidator(150),
                    catalog.validators.validators_item,
                ],
                verbose_name="Описание",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="slug",
            field=models.CharField(
                blank=True,
                default="",
                validators=[django.core.validators.MaxLengthValidator(150)],
                verbose_name="Слаг",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(unique=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(
                help_text="Имя должнобыть больше, чем из 2х букв",
                validators=[django.core.validators.MinLengthValidator(2)],
                verbose_name="Имя",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                help_text="Имя должнобыть больше, чем из 2х букв",
                unique=True,
                validators=[django.core.validators.MinLengthValidator(2)],
                verbose_name="Имя",
            ),
        ),
    ]
