# Generated by Django 5.2 on 2026-08-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0007_category_slug_item_text_tag_slug_alter_category_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tag",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
